// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUWNHKPf2dLuixPCNKyEebXK-owhDLG1E',
    appId: '1:647543444368:web:8ae771c7cb2d098f049915',
    messagingSenderId: '647543444368',
    projectId: 'codeshare-49d85',
    authDomain: 'codeshare-49d85.firebaseapp.com',
    storageBucket: 'codeshare-49d85.appspot.com',
    measurementId: 'G-BPW482MVR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADrONfsvB1j3eRYPLHp0HxsTpUOAt2OIc',
    appId: '1:647543444368:android:b6a841b767291b0e049915',
    messagingSenderId: '647543444368',
    projectId: 'codeshare-49d85',
    storageBucket: 'codeshare-49d85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXgKIlNbGskuNJiNxBQqLlosUgdSKMekQ',
    appId: '1:647543444368:ios:160f7ea3118d87e2049915',
    messagingSenderId: '647543444368',
    projectId: 'codeshare-49d85',
    storageBucket: 'codeshare-49d85.appspot.com',
    iosBundleId: 'com.example.codeShare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXgKIlNbGskuNJiNxBQqLlosUgdSKMekQ',
    appId: '1:647543444368:ios:7968631c19c2e717049915',
    messagingSenderId: '647543444368',
    projectId: 'codeshare-49d85',
    storageBucket: 'codeshare-49d85.appspot.com',
    iosBundleId: 'com.example.codeShare.RunnerTests',
  );
}
